### ISSUE TITLE
Can not divide `Number[np.ndarray]` by `np.ndarray` or `Number[np.ndarray]` (without unc.)

### ISSUE THREAD

**Issue by pfackeldey** [riga/scinum#13]
Hi @riga ,

basically as the title says, I suspect that also other operations might be affected by this.

See the following example:
```python
In [1]: n = Number(np.array([1, 2, 3]), np.array([0.1, 0.1, 0.1]))

In [2]: a = np.array([10, 10, 10])

In [3]: n / a  # fails
...
   1714             unc2[non_zero] = unc2[non_zero] / nom2[non_zero]
   1715             unc2[~non_zero] = 0.
-> 1716         elif nom2:
   1717             unc2 = unc2 / nom2
   1718         else:

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [4]: n / Number(a)  # fails
...
   1714             unc2[non_zero] = unc2[non_zero] / nom2[non_zero]
   1715             unc2[~non_zero] = 0.
-> 1716         elif nom2:
   1717             unc2 = unc2 / nom2
   1718         else:

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [7]: n / Number(a, np.array([0, 0, 0]))  # works
Out[7]: <Number at 0x7f11e8375460, numpy array, shape (3,), 1 uncertainties>
```

It seems that casting it to a `Number` object without an explicit uncertainty does not work either as the uncertainty is created as `float(0)` instead of `np.zeros_like(<nominal>)` and thus failing the following condition: https://github.com/riga/scinum/blob/master/scinum.py#L1872

Best, Peter

**Comment by riga** [comment]
Hi @pfackeldey ,

thanks for reporting! Turned out, a clearer separation between built-on and custom-ops was required, but this is fixed now. Can you test on your side?

**Comment by riga** [comment]
Ah, I took your example and made it a test case which is running now. I'm going ahead and close. 👍
