### ISSUE TITLE
`repr` and rounding

### ISSUE THREAD

**Issue by adavidzh** [riga/scinum#4]
If I understand correctly, there is presently no provision to perform "proper" round of values. I would like to contribute [Rounding.py.zip](https://github.com/riga/scinum/files/1362711/Rounding.py.zip). I wrote this quite some time ago because I was tired of seeing the wrong things done. I think that `scinum` would be a good home for that and if you have pointers on how to integrate it, it would be great.

**Comment by riga** [comment]
Hi! That would be indeed a great feature. We can forward the arguments of `repr()` to your `roundUnc` function and also add the other helper functions for convenience at the bottom of [scinum.py](https://github.com/riga/scinum/blob/master/scinum.py). I can create a draft feature branch later and keep you up-to-date.

**Comment by riga** [comment]
@adavidzh I'm a bit confused about the "Publication" method in case of significant digits >= 950 (from [here](http://pdg.lbl.gov/2011/reviews/rpp2011-rev-rpp-intro.pdf#page=13)). Example:

```python
# a
round_uncertainty(0.962, "Publication") # ->("96", -2)
# b
round_uncertainty(0.962, "Publication") # ->("962", -3)
```

Is a or b the behavior you intended?

**Comment by adavidzh** [comment]
The idea is that
> "Publication" is like "PDG" with an extra significant digit (for results that need to be combined later)

Since PDG rules would round 0.962 as `a`, "Publication" would be `b`.

**Comment by riga** [comment]
Ah ok, I thought that "PDG" would round 0.962 as `("10", -1)` due to that rounding to 1000.

**Comment by adavidzh** [comment]
Hm. What was I thinking? You’re right. In any case, Publication = PDG + 1.

**Comment by riga** [comment]
I finally found some time to implement this.

**Comment by adavidzh** [comment]
Nice!
